# Generated by Django 5.2 on 2025-04-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Menu',
        ),
    ]
